# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    program_builder.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/12 11:04:11 by umeneses          #+#    #+#              #
#    Updated: 2024/07/15 12:58:57 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: program_builder

on:
  push:
    branches:
    - main
    - '**feature**'
    - '**feat**'
    - '**bugfix**'
    - '**fix**'
    - '**release**'
  pull_request:
    branches:
    - main
    - '**feature**'
    - '**feat**'
    - '**bugfix**'
    - '**fix**'
    - '**release**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Starting Github Actions
        uses: actions/checkout@v4.1.4
      
      - name: Building Program with MiniShell Makefile
        run: make
      
      - name: Setup Aptitude
        run: sudo apt-get update && sudo apt install aptitude -y
      
      - name: Setup Valgrind
        run: sudo aptitude install -y valgrind
      
      - name: Running Valgrind
        id: valgrind_check
        run: |
          valgrind --track-origins=yes --leak-check=full --suppressions=./readline.sup -q ./minishell || true
      
      - name: Check Valgrind Output
        run: |
          echo "${{ steps.valgrind_check.outputs.stdout }}" | grep -q "ERROR SUMMARY: 0 errors from 0 contexts" && echo "Valgrind check passed" || echo "Valgrind check failed"
      
      - name: Check Valgrind Output
        run: |
          echo "VALGRIND_EXIT_CODE=$?" >> $GITHUB_ENV
      
      - name: Fail Job if Memory Leaks Detected
        run: |
          if [ "$VALGRIND_EXIT_CODE" != "0" ]; then
            echo "Memory leaks detected, failing the job."
            exit 1
          fi

      - name: Install Python for Norminette
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip setuptools
      
      - name: Install Norminette
        run: python -m pip install norminette

      - name: Running Norminette
        run: norminette -R CheckForbiddenSourceHeader ./headers/ ./libs/ ./src/

# :: github actions documentation ::
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions