# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    program_builder.yml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/12 11:04:11 by umeneses          #+#    #+#              #
#    Updated: 2024/06/12 11:37:33 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: program_builder

on:
  push:
    branches:
    - main
    - 'feature/**'
    - 'feat/**'
    - 'bugfix/**'
    - 'release/**'
  pull_request:
    branches:
    - main
    - 'feature/**'
    - 'feat/**'
    - 'bugfix/**'
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Starting Github Actions
        uses: actions/checkout@v4.1.4
      
      - name: Building Program with MiniShell Makefile
        run: make
      
      - name: Setup Aptitude
        run: sudo apt install aptitude && sudo aptitude update && sudo aptitude upgrade
      
      - name: Setup Valgrind
        run: sudo aptitude install -y valgrind
      
      - name: Running Valgrind
        run: valgrind --track-origins=yes --leak-check=full -q ./minishell

      - name: Install Python for Norminette
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip setuptools
      
      - name: Install Norminette
        run: python -m pip install norminette

      - name: Running Norminette
        run: norminette -R CheckForbiddenSourceHeader ./headers/ ./libs/ ./src/

# :: github actions documentation ::
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions